version: "3.9"

services:
  calculate_bonus_service:
    restart: always
    build: .
    ports:
      - "8800:8000"  # Публикуем порт для прямого доступа
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: pg_container
    environment:
      - POSTGRES_USER = ${POSTGRES_USER}
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
      - POSTGRES_DB = ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"  # Публикуем порт 80 для Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Монтируем конфиг Nginx
    depends_on:
      - calculate_bonus_service

volumes:
  db_data: # Именованный том для хранения данных БД